### ISSUE TITLE
Doesn't  pass the required parameter in to_hex() action.

### ISSUE THREAD

**Issue by nirdesh27** [MitchPierias/Advanced-EOS-Examples#21]
Hi MitchPierias
In your t0_hex();  action  you didn't pass the parameter{length}
		void hash(const string& str) {
			// Hash the given string
			checksum256 hashed = create_hash(str);
			// Convert output to hexadecimal string
			string result = t**o_hex(hashed);** //length is required.
			// Print result
			print(result);
		}

although there is no need to pass length here because we already know the length of sha256, but you take it as a params in **to_hex()** action. One more thing this series  is nice to understand EOS tables.
Thanks Man

**Comment by nirdesh27** [comment]
Brother did you change  this issue?

**Comment by MitchPierias** [comment]
Thanks brother, this has since been repaired and a secondary issue referencing the incorrect variable for `sha256` within the `createHash` function. I'm having a bug my end compiling though. Something to do with the class and I believe the template definition.
