### ISSUE TITLE
Upgrade to latest CDT

### ISSUE THREAD

**Issue by thekevinbrown** [MitchPierias/Advanced-EOS-Examples#22]
It'd be great to upgrade these examples to use the latest CDT so when people copy / paste into their latest environments they don't get build errors.

I'd be happy to help if that's a thing you're interested in doing.

**Comment by MitchPierias** [comment]
Hi Kevin, thank you for reaching out. This is definitely something I'm looking into and I'd really appreciate the help. I haven't had the time, and won't for another 4 weeks. But if you'd like to start contributing, I'd be happy to review and merge your changes in. I'll send you an email now as well to touch base. Thanks again!
